FROM test-env-base:centos7

ARG DB_NAME=ICAT
ARG DB_PASSWORD=testpassword
ARG DB_USER=irods
ARG DBMS_HOST=dbms_configured
ARG DBMS_PORT=5432
ARG DBMS_TYPE=postgres
ARG IRODS_CONTROL_PLANE_KEY=TEMPORARY__32byte_ctrl_plane_key
ARG IRODS_CONTROL_PLANE_PORT=1248
ARG IRODS_DEFAULT_RESOURCE=demoResc
ARG IRODS_FIRST_EPHEMERAL_PORT=20000
ARG IRODS_HOST=csp
ARG IRODS_LAST_EPHEMERAL_PORT=20199
ARG IRODS_NEGOTIATION_KEY=TEMPORARY_32byte_negotiation_key
ARG IRODS_SCHEMA_VALIDATION=https://schemas.irods.org/configuration
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_KEY=TEMPORARY_zone_key
ARG IRODS_ZONE_NAME=tempZone
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247
ARG IRODS_ZONE_USER=rods

COPY <<EOF /etc/yum.repos.d/pgdg-12.repo
[pgdg12-archive]
name=PostgreSQL 12 RPMs for RHEL/Rocky Linux/AlmaLinux/CentOS 7
baseurl=https://yum-archive.postgresql.org/12/redhat/rhel-7-x86_64
enabled=1
gpgcheck=0
EOF

ADD https://packages.irods.org/renci-irods.yum.repo /etc/yum.repos.d/renci-irods.yum.repo

COPY irods-provider/config/pre_config.re /etc/irods/

RUN \
	--mount=target=/tmp/config-irods,source=irods-provider/scripts/config-irods.sh \
	--mount=target=/tmp/service.sh.template,source=irods-provider/scripts/service.sh.template \
	--mount=target=/tmp/prep-svc-script,source=irods-provider/scripts/prep-svc-script.sh \
<<EOF
	set -o errexit

### Install PostgreSQL ODBC connector
	yum --assumeyes install postgresql12-odbc

### Install iRODS
	rpm --import https://packages.irods.org/irods-signing-key.asc
	yum --assumeyes versionlock add \
		irods-database-plugin-postgres-4.3.1 \
		irods-icommands-4.3.1 \
		irods-netcdf-client_modules-4.3.1.0 \
		irods-netcdf-icommands-4.3.1.0 \
		irods-netcdf-server_modules-4.3.1.0 \
		irods-runtime-4.3.1 \
		irods-server-4.3.1
# XXX - python3-pyodbc required by irods-server but not available as system package in CentOS 7
	yum --assumeyes install gcc gcc-c++ unixODBC-devel
	pip3 install pyodbc
	yum --assumeyes erase gcc gcc-c++ unixODBC-devel
# XXX - ^^^
# XXX - irods-icommands required by irods-server but not installed by dependency resolution in
#       CentOS 7, 4.3.1
	yum --assumeyes install irods-icommands
# XXX - ^^^
	yum --assumeyes install \
		irods-database-plugin-postgres \
		irods-netcdf-client_modules \
		irods-netcdf-icommands \
		irods-netcdf-server_modules \
		irods-server \
		rsyslog

### Install libraries required by command scripts
	pip3 install 'pika>=1.2'

### Configure ODBC and iRODS
	/tmp/config-irods

### Create service script
	/tmp/prep-svc-script

### Install testing support artifacts
	pip3 --quiet install 'python-irodsclient<3.2'

### Add fake s3 credentials
	mkdir --parents /etc/irods/s3-credentials
	touch /etc/irods/s3-credentials/cred-stale
	chown --recursive irods /etc/irods/s3-credentials

### Clean yum cache
	yum clean all
	rm --force --recursive /var/cache/yum
EOF

COPY irods-provider/config/profile-irods.sh /etc/profile.d/irods.sh
COPY irods-provider/config/rsyslog-irods.conf /etc/rsyslog.conf
COPY irods-provider/config/logrotate-irods /etc/logrotate.d/irods

CMD [ "/service.sh" ]
