#!/usr/bin/env bash
#
# Usage:
#  controller INC_FILE (start|stop) [OVERRIDE_FILE ...]
#
# PARAMETERS:
#  INC_FILE       The absolute path to a file including the build time
#                 environment variables. See README.md for details.
#  OVERRIDE_FILE  A compose file to apply over docker-compose.yml, e.g.,
#                 docker-compose.provider-alma9.yml. Pass the same ones to stop
#                 as to start.
#
# Starts or stops all of the containers.

set -o errexit -o nounset -o pipefail

ExecName=$(readlink -f "$0")
readonly ExecName

#shellcheck source=testing/portability.inc
. "$(dirname "$ExecName")"/../portability.inc


main()
{
  local baseDir
  baseDir=$(dirname "$ExecName")

  if [ "$#" -lt 1 ]
  then
    printf 'An environment variable include file is required as its first parameter.\n' >&2
    return 1
  fi

  local cfg="$1"

  if [ "$#" -lt 2 ]
  then
    printf 'Requires either "start" or "stop" as its second parameter.\n' >&2
    return 1
  fi

  local action="$2"
  shift 2

  if ! [[ "$cfg" =~ ^/ ]]
  then
    cfg="$(pwd)"/"$cfg"
  fi

  # shellcheck disable=SC1090
  . "$cfg"

  local dcCmd
  case "$action" in
    start)
      dcCmd=(up -d --scale dbms_unconfigured=2)
      ;;
    stop)
      dcCmd=(down --remove-orphans --volumes)
      ;;
    *)
      printf 'Unknown command "%s"\n' "$action" >&2
      return 1
      ;;
  esac

  local composeArgs=(--file="$baseDir"/docker-compose.yml)

  local override
  for override in "$@"
  do
    composeArgs+=(--file="$override")
  done

  composeArgs+=(--project-name="$ENV_NAME" "${dcCmd[@]}")

  ds_compose "${composeArgs[@]}"
}


main "$@"
